build: off
clone_folder: c:\gopath\src\github.com\code-ready\crc
environment:
  GOPATH: c:\gopath
stack: go 1.14
before_test:
  - choco install mingw
  - choco install make
  - choco install wixtoolset
  - set PATH=%PATH%;"C:\Program Files (x86)\WiX Toolset v3.11\bin"
  - refreshenv
  - make MOCK_BUNDLE=true BUNDLE_DIR=./ out/windows-amd64/crc-installer.zip
  - make cross
test_script:
  - make test
