## Circleci version
version: 2

## Machine specific variable
jobs:
  build:
    macos:
      xcode: "10.0.0"
    environment:
      GOVERSION: "1.11.6"

## Build crc
    steps:
    - checkout
    - run:
        name: Configure GOPATH
        command: echo 'export GOPATH=$HOME/go' >> $BASH_ENV
    - run:
        name: Configure Path
        command: echo 'export PATH=$GOPATH/bin:/usr/local/go/bin/:$PATH' >> $BASH_ENV
    - run:
        name: Cleanup GOROOT
        command: sudo rm -rf /usr/local/go
    - run:
        name: Install go
        command: curl https://dl.google.com/go/go${GOVERSION}.darwin-amd64.tar.gz | sudo tar -C /usr/local -xz
    - run:
        name: List go version
        command: go version
    - run:
        name: List go environment
        command: go env
    - run:
        name: Make
        command: make
    - run:
        name: Make fmtcheck
        command: make fmtcheck
    - run:
        name: Make cross
        command: make cross
    - run:
        name: Run unit tests
        command: make test
    - store_artifacts:
        path: ~/project/out
        destination: crc
