## Circleci version
version: 2

## Machine specific variable
jobs:
  build:
    macos:
      xcode: "10.0.0"
    environment:
      GOVERSION: "1.11.6"

## Build crc
    steps:
    - checkout
    - run:
        name: Configure GOPATH
        command: echo 'export GOPATH=$HOME/go' >> $BASH_ENV
    - run:
        name: Configure Path
        command: echo 'export PATH=$GOPATH/bin:/usr/local/go/bin/:$PATH' >> $BASH_ENV
    - run:
        name: Cleanup GOROOT
        command: sudo rm -rf /usr/local/go
    - run:
        name: Install go
        command: curl https://dl.google.com/go/go${GOVERSION}.darwin-amd64.tar.gz | sudo tar -C /usr/local -xz
    - run:
        name: List go version
        command: go version
    - run:
        name: List go environment
        command: go env
    - run:
        name: Make
        command: make
    - run:
        name: Make fmtcheck
        command: make fmtcheck
    - run:
        name: Make cross
        command: make cross
    - run:
        name: Run unit tests
        command: make test
    - store_artifacts:
        path: ~/project/out
        destination: crc

  build_docs:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - checkout
    - run:
        name: Update repo
        command: sudo apt -y update
    - run:
        name: Add podman ppa
        command: sudo add-apt-repository -y ppa:projectatomic/ppa && sudo apt -y update
    - run:
        name: Update repo
        command: sudo apt -y update
    - run:
        name: Install podman
        command: sudo apt -y install podman
    - run:
        name: Check podman
        command: podman info
    - run:
        name: Make build_docs
        command: make build_docs
    - persist_to_workspace:
        root: docs/
        paths: build

  docs_deploy:
    docker:
      - image: node:8.10.0
    steps:
    - checkout
    - attach_workspace:
        at: docs/build
    - add_ssh_keys:
        fingerprints:
          - "c5:64:d4:79:8f:c7:9b:80:b8:16:71:20:57:6b:8c:94"
    - run:
        name: Install and configure dependencies
        command: |
          npm install -g --silent gh-pages@2.0.1
          git config user.email "codereadycontainers@gmail.com"
          git config user.name "crc-bot"
    - run:
        name: Deploy docs to gh-pages branch
        command: gh-pages -d docs/build/* -s *.html --message "[skip ci] Docs update"

workflows:
  version: 2
  build:
    jobs:
      - build
      - build_docs
      - docs_deploy:
          requires:
            - build
            - build_docs
          filters:
            branches:
              only: master
